-- Inventory transactions and audit trail.

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint not null references public.products(id) on delete restrict,
  location_id bigint not null references public.inventory_locations(id) on delete restrict,
  movement_type text not null default 'adjustment',
  delta_on_hand integer not null default 0,
  delta_reserved integer not null default 0,
  on_hand_before integer not null,
  on_hand_after integer not null,
  reserved_before integer not null,
  reserved_after integer not null,
  reason text,
  order_id bigint references public.orders(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  metadata jsonb,
  constraint inventory_transactions_movement_type_check check (
    movement_type in (
      'receipt',
      'sale',
      'adjustment',
      'return',
      'transfer_in',
      'transfer_out',
      'reservation',
      'release',
      'damage'
    )
  ),
  constraint inventory_transactions_delta_check check (delta_on_hand <> 0 or delta_reserved <> 0),
  constraint inventory_transactions_non_negative check (
    on_hand_after >= 0 and reserved_after >= 0 and reserved_after <= on_hand_after
  )
);

create index if not exists idx_inventory_transactions_product
  on public.inventory_transactions (product_id);
create index if not exists idx_inventory_transactions_location
  on public.inventory_transactions (location_id);
create index if not exists idx_inventory_transactions_created_at
  on public.inventory_transactions (created_at desc);

create or replace function public.adjust_inventory(
  p_product_id bigint,
  p_location_id bigint,
  p_delta_on_hand integer,
  p_delta_reserved integer default 0,
  p_movement_type text default 'adjustment',
  p_reason text default null,
  p_order_id bigint default null,
  p_metadata jsonb default null,
  p_created_by uuid default null
)
returns table (
  transaction_id bigint,
  on_hand integer,
  reserved integer,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_on_hand integer;
  v_current_reserved integer;
  v_new_on_hand integer;
  v_new_reserved integer;
  v_status text;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Only admins can adjust inventory.';
  end if;

  select on_hand, reserved
    into v_current_on_hand, v_current_reserved
  from public.inventory_levels
  where product_id = p_product_id
    and location_id = p_location_id
  for update;

  if v_current_on_hand is null then
    v_current_on_hand := 0;
  end if;
  if v_current_reserved is null then
    v_current_reserved := 0;
  end if;

  v_new_on_hand := v_current_on_hand + coalesce(p_delta_on_hand, 0);
  v_new_reserved := v_current_reserved + coalesce(p_delta_reserved, 0);

  if v_new_on_hand < 0 or v_new_reserved < 0 or v_new_reserved > v_new_on_hand then
    raise exception 'Invalid inventory adjustment.';
  end if;

  v_status := case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end;

  insert into public.inventory_levels (
    product_id,
    location_id,
    on_hand,
    reserved,
    status
  )
  values (
    p_product_id,
    p_location_id,
    v_new_on_hand,
    v_new_reserved,
    v_status
  )
  on conflict (product_id, location_id)
  do update set
    on_hand = excluded.on_hand,
    reserved = excluded.reserved,
    status = excluded.status;

  insert into public.inventory_transactions (
    product_id,
    location_id,
    movement_type,
    delta_on_hand,
    delta_reserved,
    on_hand_before,
    on_hand_after,
    reserved_before,
    reserved_after,
    reason,
    order_id,
    created_by,
    metadata
  )
  values (
    p_product_id,
    p_location_id,
    coalesce(p_movement_type, 'adjustment'),
    coalesce(p_delta_on_hand, 0),
    coalesce(p_delta_reserved, 0),
    v_current_on_hand,
    v_new_on_hand,
    v_current_reserved,
    v_new_reserved,
    p_reason,
    p_order_id,
    coalesce(auth.uid(), p_created_by),
    p_metadata
  )
  returning id into transaction_id;

  on_hand := v_new_on_hand;
  reserved := v_new_reserved;
  status := v_status;
  return next;
end;
$$;

create or replace function public.reserve_inventory_for_order(
  p_order_id bigint,
  p_location_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_location_id bigint;
  v_user_id uuid;
  v_item record;
  v_on_hand integer;
  v_reserved integer;
  v_new_on_hand integer;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to reserve inventory.';
  end if;

  if exists (
    select 1
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'sale'
  ) then
    return;
  end if;

  select user_id
    into v_user_id
  from public.orders
  where id = p_order_id;

  select coalesce(
    p_location_id,
    (
      select id
      from public.inventory_locations
      where is_active = true
      order by id
      limit 1
    )
  )
  into v_location_id;

  if v_location_id is null then
    raise exception 'No active inventory location available.';
  end if;

  for v_item in
    select product_id, quantity
    from public.order_items
    where order_id = p_order_id
  loop
    select on_hand, reserved
      into v_on_hand, v_reserved
    from public.inventory_levels
    where product_id = v_item.product_id
      and location_id = v_location_id
    for update;

    if v_on_hand is null then
      v_on_hand := 0;
    end if;
    if v_reserved is null then
      v_reserved := 0;
    end if;

    v_new_on_hand := v_on_hand - v_item.quantity;
    if v_new_on_hand < 0 then
      raise exception 'Insufficient stock for product %', v_item.product_id;
    end if;

    insert into public.inventory_levels (
      product_id,
      location_id,
      on_hand,
      reserved,
      status
    )
    values (
      v_item.product_id,
      v_location_id,
      v_new_on_hand,
      v_reserved,
      case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end
    )
    on conflict (product_id, location_id)
    do update set
      on_hand = excluded.on_hand,
      reserved = excluded.reserved,
      status = excluded.status;

    insert into public.inventory_transactions (
      product_id,
      location_id,
      movement_type,
      delta_on_hand,
      delta_reserved,
      on_hand_before,
      on_hand_after,
      reserved_before,
      reserved_after,
      reason,
      order_id,
      created_by,
      metadata
    )
    values (
      v_item.product_id,
      v_location_id,
      'sale',
      -v_item.quantity,
      0,
      v_on_hand,
      v_new_on_hand,
      v_reserved,
      v_reserved,
      'Order placed',
      p_order_id,
      v_user_id,
      jsonb_build_object('source', 'order')
    );
  end loop;
end;
$$;

create or replace function public.restock_inventory_for_order(
  p_order_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_on_hand integer;
  v_reserved integer;
  v_new_on_hand integer;
  v_new_reserved integer;
  v_user_id uuid;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to restock inventory.';
  end if;

  if exists (
    select 1
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'return'
  ) then
    return;
  end if;

  select user_id
    into v_user_id
  from public.orders
  where id = p_order_id;

  for v_item in
    select product_id,
           location_id,
           sum(delta_on_hand) as delta_on_hand,
           sum(delta_reserved) as delta_reserved
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'sale'
    group by product_id, location_id
  loop
    select on_hand, reserved
      into v_on_hand, v_reserved
    from public.inventory_levels
    where product_id = v_item.product_id
      and location_id = v_item.location_id
    for update;

    if v_on_hand is null then
      v_on_hand := 0;
    end if;
    if v_reserved is null then
      v_reserved := 0;
    end if;

    v_new_on_hand := v_on_hand - v_item.delta_on_hand;
    v_new_reserved := v_reserved - v_item.delta_reserved;

    if v_new_on_hand < 0 or v_new_reserved < 0 or v_new_reserved > v_new_on_hand then
      raise exception 'Invalid restock adjustment for product %', v_item.product_id;
    end if;

    update public.inventory_levels
      set on_hand = v_new_on_hand,
          reserved = v_new_reserved,
          status = case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end
    where product_id = v_item.product_id
      and location_id = v_item.location_id;

    insert into public.inventory_transactions (
      product_id,
      location_id,
      movement_type,
      delta_on_hand,
      delta_reserved,
      on_hand_before,
      on_hand_after,
      reserved_before,
      reserved_after,
      reason,
      order_id,
      created_by,
      metadata
    )
    values (
      v_item.product_id,
      v_item.location_id,
      'return',
      -v_item.delta_on_hand,
      -v_item.delta_reserved,
      v_on_hand,
      v_new_on_hand,
      v_reserved,
      v_new_reserved,
      'Order cancelled',
      p_order_id,
      v_user_id,
      jsonb_build_object('source', 'order')
    );
  end loop;
end;
$$;

create or replace function public.cancel_order_and_restock(
  p_order_id bigint
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to cancel order.';
  end if;

  select *
    into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'Order not found.';
  end if;

  if v_order.status = 'Cancelled' then
    return v_order;
  end if;

  if v_order.status not in ('Pending Payment', 'New', 'Cooking', 'Delivering') then
    raise exception 'Order cannot be cancelled from status %', v_order.status;
  end if;

  perform public.restock_inventory_for_order(p_order_id);

  update public.orders
    set status = 'Cancelled'
  where id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

alter table public.inventory_transactions enable row level security;

drop policy if exists "inventory_transactions read admin" on public.inventory_transactions;
create policy "inventory_transactions read admin"
on public.inventory_transactions
for select
to authenticated
using (public.is_admin());

drop policy if exists "inventory_transactions insert admin" on public.inventory_transactions;
create policy "inventory_transactions insert admin"
on public.inventory_transactions
for insert
to authenticated
with check (public.is_admin());

grant select, insert on table public.inventory_transactions to authenticated, service_role;
grant execute on function public.adjust_inventory(
  bigint,
  bigint,
  integer,
  integer,
  text,
  text,
  bigint,
  jsonb,
  uuid
) to authenticated, service_role;
grant execute on function public.reserve_inventory_for_order(
  bigint,
  bigint
) to authenticated, service_role;
grant execute on function public.restock_inventory_for_order(
  bigint
) to authenticated, service_role;
grant execute on function public.cancel_order_and_restock(
  bigint
) to authenticated, service_role;
