
  create table "public"."inventory_alerts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "resolved_at" timestamp with time zone,
    "acknowledged_at" timestamp with time zone,
    "acknowledged_by" uuid,
    "product_id" bigint not null,
    "location_id" bigint not null,
    "alert_type" text not null default 'low_stock'::text,
    "severity" text not null default 'warning'::text,
    "status" text not null default 'active'::text,
    "on_hand" integer not null default 0,
    "reserved" integer not null default 0,
    "available" integer not null default 0,
    "reorder_point" integer not null default 0,
    "safety_stock" integer not null default 0,
    "note" text,
    "metadata" jsonb
      );


alter table "public"."inventory_alerts" enable row level security;


  create table "public"."inventory_levels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "product_id" bigint not null,
    "location_id" bigint not null,
    "on_hand" integer not null default 0,
    "reserved" integer not null default 0,
    "status" text not null default 'available'::text
      );


alter table "public"."inventory_levels" enable row level security;


  create table "public"."inventory_locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null,
    "code" text,
    "address" text,
    "is_active" boolean not null default true
      );


alter table "public"."inventory_locations" enable row level security;


  create table "public"."inventory_transactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "product_id" bigint not null,
    "location_id" bigint not null,
    "movement_type" text not null default 'adjustment'::text,
    "delta_on_hand" integer not null default 0,
    "delta_reserved" integer not null default 0,
    "on_hand_before" integer not null,
    "on_hand_after" integer not null,
    "reserved_before" integer not null,
    "reserved_after" integer not null,
    "reason" text,
    "order_id" bigint,
    "created_by" uuid,
    "metadata" jsonb
      );


alter table "public"."inventory_transactions" enable row level security;


  create table "public"."reorder_rules" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "product_id" bigint not null,
    "location_id" bigint not null,
    "supplier_id" bigint,
    "reorder_point" integer not null default 0,
    "safety_stock" integer not null default 0,
    "lead_time_days" integer not null default 0,
    "is_active" boolean not null default true
      );


alter table "public"."reorder_rules" enable row level security;


  create table "public"."suppliers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "contact_email" text,
    "contact_phone" text,
    "lead_time_days" integer not null default 0,
    "is_active" boolean not null default true
      );


alter table "public"."suppliers" enable row level security;

alter table "public"."delivery_settings" add column "fulfillment_location_id" bigint;

alter table "public"."products" add column "barcode" text;

alter table "public"."products" add column "sku" text;

alter table "public"."products" add column "track_inventory" boolean not null default true;

alter table "public"."products" add column "unit_cost" numeric not null default 0;

alter table "public"."profiles" drop column if exists "expo_push_token";

CREATE INDEX idx_delivery_settings_fulfillment_location ON public.delivery_settings USING btree (fulfillment_location_id);

CREATE UNIQUE INDEX idx_inventory_alerts_active_unique ON public.inventory_alerts USING btree (product_id, location_id, alert_type) WHERE (status = ANY (ARRAY['active'::text, 'acknowledged'::text]));

CREATE INDEX idx_inventory_alerts_created_at ON public.inventory_alerts USING btree (created_at DESC);

CREATE INDEX idx_inventory_alerts_location ON public.inventory_alerts USING btree (location_id);

CREATE INDEX idx_inventory_levels_location ON public.inventory_levels USING btree (location_id);

CREATE INDEX idx_inventory_levels_product ON public.inventory_levels USING btree (product_id);

CREATE INDEX idx_inventory_transactions_created_at ON public.inventory_transactions USING btree (created_at DESC);

CREATE INDEX idx_inventory_transactions_location ON public.inventory_transactions USING btree (location_id);

CREATE INDEX idx_inventory_transactions_product ON public.inventory_transactions USING btree (product_id);

CREATE INDEX idx_reorder_rules_location ON public.reorder_rules USING btree (location_id);

CREATE INDEX idx_reorder_rules_product ON public.reorder_rules USING btree (product_id);

CREATE UNIQUE INDEX inventory_alerts_pkey ON public.inventory_alerts USING btree (id);

CREATE UNIQUE INDEX inventory_levels_pkey ON public.inventory_levels USING btree (id);

CREATE UNIQUE INDEX inventory_levels_unique_product_location ON public.inventory_levels USING btree (product_id, location_id);

CREATE UNIQUE INDEX inventory_locations_code_key ON public.inventory_locations USING btree (code);

CREATE UNIQUE INDEX inventory_locations_pkey ON public.inventory_locations USING btree (id);

CREATE UNIQUE INDEX inventory_transactions_pkey ON public.inventory_transactions USING btree (id);

CREATE UNIQUE INDEX reorder_rules_pkey ON public.reorder_rules USING btree (id);

CREATE UNIQUE INDEX reorder_rules_unique_product_location ON public.reorder_rules USING btree (product_id, location_id);

CREATE UNIQUE INDEX suppliers_pkey ON public.suppliers USING btree (id);

CREATE UNIQUE INDEX suppliers_unique_name ON public.suppliers USING btree (name);

alter table "public"."inventory_alerts" add constraint "inventory_alerts_pkey" PRIMARY KEY using index "inventory_alerts_pkey";

alter table "public"."inventory_levels" add constraint "inventory_levels_pkey" PRIMARY KEY using index "inventory_levels_pkey";

alter table "public"."inventory_locations" add constraint "inventory_locations_pkey" PRIMARY KEY using index "inventory_locations_pkey";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_pkey" PRIMARY KEY using index "inventory_transactions_pkey";

alter table "public"."reorder_rules" add constraint "reorder_rules_pkey" PRIMARY KEY using index "reorder_rules_pkey";

alter table "public"."suppliers" add constraint "suppliers_pkey" PRIMARY KEY using index "suppliers_pkey";

alter table "public"."delivery_settings" add constraint "delivery_settings_fulfillment_location_id_fkey" FOREIGN KEY (fulfillment_location_id) REFERENCES public.inventory_locations(id) ON DELETE SET NULL not valid;

alter table "public"."delivery_settings" validate constraint "delivery_settings_fulfillment_location_id_fkey";

alter table "public"."inventory_alerts" add constraint "inventory_alerts_acknowledged_by_fkey" FOREIGN KEY (acknowledged_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."inventory_alerts" validate constraint "inventory_alerts_acknowledged_by_fkey";

alter table "public"."inventory_alerts" add constraint "inventory_alerts_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_alerts" validate constraint "inventory_alerts_location_id_fkey";

alter table "public"."inventory_alerts" add constraint "inventory_alerts_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_alerts" validate constraint "inventory_alerts_product_id_fkey";

alter table "public"."inventory_alerts" add constraint "inventory_alerts_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'acknowledged'::text, 'resolved'::text]))) not valid;

alter table "public"."inventory_alerts" validate constraint "inventory_alerts_status_check";

alter table "public"."inventory_levels" add constraint "inventory_levels_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_levels" validate constraint "inventory_levels_location_id_fkey";

alter table "public"."inventory_levels" add constraint "inventory_levels_on_hand_check" CHECK ((on_hand >= 0)) not valid;

alter table "public"."inventory_levels" validate constraint "inventory_levels_on_hand_check";

alter table "public"."inventory_levels" add constraint "inventory_levels_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_levels" validate constraint "inventory_levels_product_id_fkey";

alter table "public"."inventory_levels" add constraint "inventory_levels_reserved_check" CHECK ((reserved >= 0)) not valid;

alter table "public"."inventory_levels" validate constraint "inventory_levels_reserved_check";

alter table "public"."inventory_levels" add constraint "inventory_levels_unique_product_location" UNIQUE using index "inventory_levels_unique_product_location";

alter table "public"."inventory_locations" add constraint "inventory_locations_code_key" UNIQUE using index "inventory_locations_code_key";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_created_by_fkey";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_delta_check" CHECK (((delta_on_hand <> 0) OR (delta_reserved <> 0))) not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_delta_check";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id) ON DELETE RESTRICT not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_location_id_fkey";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_movement_type_check" CHECK ((movement_type = ANY (ARRAY['receipt'::text, 'sale'::text, 'adjustment'::text, 'return'::text, 'transfer_in'::text, 'transfer_out'::text, 'reservation'::text, 'release'::text, 'damage'::text]))) not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_movement_type_check";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_non_negative" CHECK (((on_hand_after >= 0) AND (reserved_after >= 0) AND (reserved_after <= on_hand_after))) not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_non_negative";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE SET NULL not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_order_id_fkey";

alter table "public"."inventory_transactions" add constraint "inventory_transactions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT not valid;

alter table "public"."inventory_transactions" validate constraint "inventory_transactions_product_id_fkey";

alter table "public"."reorder_rules" add constraint "reorder_rules_location_id_fkey" FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id) ON DELETE CASCADE not valid;

alter table "public"."reorder_rules" validate constraint "reorder_rules_location_id_fkey";

alter table "public"."reorder_rules" add constraint "reorder_rules_non_negative" CHECK (((reorder_point >= 0) AND (safety_stock >= 0) AND (lead_time_days >= 0))) not valid;

alter table "public"."reorder_rules" validate constraint "reorder_rules_non_negative";

alter table "public"."reorder_rules" add constraint "reorder_rules_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE not valid;

alter table "public"."reorder_rules" validate constraint "reorder_rules_product_id_fkey";

alter table "public"."reorder_rules" add constraint "reorder_rules_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL not valid;

alter table "public"."reorder_rules" validate constraint "reorder_rules_supplier_id_fkey";

alter table "public"."reorder_rules" add constraint "reorder_rules_unique_product_location" UNIQUE using index "reorder_rules_unique_product_location";

alter table "public"."suppliers" add constraint "suppliers_lead_time_check" CHECK ((lead_time_days >= 0)) not valid;

alter table "public"."suppliers" validate constraint "suppliers_lead_time_check";

alter table "public"."suppliers" add constraint "suppliers_unique_name" UNIQUE using index "suppliers_unique_name";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.acknowledge_inventory_alert(p_alert_id bigint, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to acknowledge alerts.';
  end if;

  update public.inventory_alerts
  set status = 'acknowledged',
      acknowledged_at = now(),
      acknowledged_by = auth.uid(),
      note = coalesce(p_note, note)
  where id = p_alert_id
    and status in ('active', 'acknowledged');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.adjust_inventory(p_product_id bigint, p_location_id bigint, p_delta_on_hand integer, p_delta_reserved integer DEFAULT 0, p_movement_type text DEFAULT 'adjustment'::text, p_reason text DEFAULT NULL::text, p_order_id bigint DEFAULT NULL::bigint, p_metadata jsonb DEFAULT NULL::jsonb)
 RETURNS TABLE(transaction_id bigint, on_hand integer, reserved integer, status text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_current_on_hand integer;
  v_current_reserved integer;
  v_new_on_hand integer;
  v_new_reserved integer;
  v_status text;
begin
  if not public.is_admin() then
    raise exception 'Only admins can adjust inventory.';
  end if;

  select on_hand, reserved
    into v_current_on_hand, v_current_reserved
  from public.inventory_levels
  where product_id = p_product_id
    and location_id = p_location_id
  for update;

  if v_current_on_hand is null then
    v_current_on_hand := 0;
  end if;
  if v_current_reserved is null then
    v_current_reserved := 0;
  end if;

  v_new_on_hand := v_current_on_hand + coalesce(p_delta_on_hand, 0);
  v_new_reserved := v_current_reserved + coalesce(p_delta_reserved, 0);

  if v_new_on_hand < 0 or v_new_reserved < 0 or v_new_reserved > v_new_on_hand then
    raise exception 'Invalid inventory adjustment.';
  end if;

  v_status := case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end;

  insert into public.inventory_levels (
    product_id,
    location_id,
    on_hand,
    reserved,
    status
  )
  values (
    p_product_id,
    p_location_id,
    v_new_on_hand,
    v_new_reserved,
    v_status
  )
  on conflict (product_id, location_id)
  do update set
    on_hand = excluded.on_hand,
    reserved = excluded.reserved,
    status = excluded.status;

  insert into public.inventory_transactions (
    product_id,
    location_id,
    movement_type,
    delta_on_hand,
    delta_reserved,
    on_hand_before,
    on_hand_after,
    reserved_before,
    reserved_after,
    reason,
    order_id,
    created_by,
    metadata
  )
  values (
    p_product_id,
    p_location_id,
    coalesce(p_movement_type, 'adjustment'),
    coalesce(p_delta_on_hand, 0),
    coalesce(p_delta_reserved, 0),
    v_current_on_hand,
    v_new_on_hand,
    v_current_reserved,
    v_new_reserved,
    p_reason,
    p_order_id,
    auth.uid(),
    p_metadata
  )
  returning id into transaction_id;

  on_hand := v_new_on_hand;
  reserved := v_new_reserved;
  status := v_status;
  return next;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.adjust_inventory(p_product_id bigint, p_location_id bigint, p_delta_on_hand integer, p_delta_reserved integer DEFAULT 0, p_movement_type text DEFAULT 'adjustment'::text, p_reason text DEFAULT NULL::text, p_order_id bigint DEFAULT NULL::bigint, p_metadata jsonb DEFAULT NULL::jsonb, p_created_by uuid DEFAULT NULL::uuid)
 RETURNS TABLE(transaction_id bigint, on_hand integer, reserved integer, status text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_current_on_hand integer;
  v_current_reserved integer;
  v_new_on_hand integer;
  v_new_reserved integer;
  v_status text;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Only admins can adjust inventory.';
  end if;

  select on_hand, reserved
    into v_current_on_hand, v_current_reserved
  from public.inventory_levels
  where product_id = p_product_id
    and location_id = p_location_id
  for update;

  if v_current_on_hand is null then
    v_current_on_hand := 0;
  end if;
  if v_current_reserved is null then
    v_current_reserved := 0;
  end if;

  v_new_on_hand := v_current_on_hand + coalesce(p_delta_on_hand, 0);
  v_new_reserved := v_current_reserved + coalesce(p_delta_reserved, 0);

  if v_new_on_hand < 0 or v_new_reserved < 0 or v_new_reserved > v_new_on_hand then
    raise exception 'Invalid inventory adjustment.';
  end if;

  v_status := case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end;

  insert into public.inventory_levels (
    product_id,
    location_id,
    on_hand,
    reserved,
    status
  )
  values (
    p_product_id,
    p_location_id,
    v_new_on_hand,
    v_new_reserved,
    v_status
  )
  on conflict (product_id, location_id)
  do update set
    on_hand = excluded.on_hand,
    reserved = excluded.reserved,
    status = excluded.status;

  insert into public.inventory_transactions (
    product_id,
    location_id,
    movement_type,
    delta_on_hand,
    delta_reserved,
    on_hand_before,
    on_hand_after,
    reserved_before,
    reserved_after,
    reason,
    order_id,
    created_by,
    metadata
  )
  values (
    p_product_id,
    p_location_id,
    coalesce(p_movement_type, 'adjustment'),
    coalesce(p_delta_on_hand, 0),
    coalesce(p_delta_reserved, 0),
    v_current_on_hand,
    v_new_on_hand,
    v_current_reserved,
    v_new_reserved,
    p_reason,
    p_order_id,
    coalesce(auth.uid(), p_created_by),
    p_metadata
  )
  returning id into transaction_id;

  on_hand := v_new_on_hand;
  reserved := v_new_reserved;
  status := v_status;
  return next;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.cancel_order_and_restock(p_order_id bigint)
 RETURNS public.orders
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_order public.orders;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to cancel order.';
  end if;

  select *
    into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'Order not found.';
  end if;

  if v_order.status = 'Cancelled' then
    return v_order;
  end if;

  if v_order.status not in ('Pending Payment', 'New', 'Cooking', 'Delivering') then
    raise exception 'Order cannot be cancelled from status %', v_order.status;
  end if;

  perform public.restock_inventory_for_order(p_order_id);

  update public.orders
    set status = 'Cancelled'
  where id = p_order_id
  returning * into v_order;

  return v_order;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_inventory_alerts(p_location_id bigint DEFAULT NULL::bigint)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_inserted integer := 0;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to generate alerts.';
  end if;

  -- Resolve alerts where stock is back above reorder point.
  update public.inventory_alerts a
  set status = 'resolved',
      resolved_at = now()
  from public.inventory_levels l
  join public.reorder_rules r
    on r.product_id = l.product_id
   and r.location_id = l.location_id
   and r.is_active
  where a.product_id = l.product_id
    and a.location_id = l.location_id
    and a.alert_type = 'low_stock'
    and a.status in ('active', 'acknowledged')
    and (l.on_hand - l.reserved) > r.reorder_point
    and (p_location_id is null or l.location_id = p_location_id);

  insert into public.inventory_alerts (
    product_id,
    location_id,
    alert_type,
    severity,
    status,
    on_hand,
    reserved,
    available,
    reorder_point,
    safety_stock,
    note,
    metadata
  )
  select
    l.product_id,
    l.location_id,
    'low_stock',
    case
      when (l.on_hand - l.reserved) <= r.safety_stock then 'critical'
      else 'warning'
    end,
    'active',
    l.on_hand,
    l.reserved,
    (l.on_hand - l.reserved) as available,
    r.reorder_point,
    r.safety_stock,
    'Reorder point reached',
    jsonb_build_object(
      'lead_time_days',
      coalesce(nullif(r.lead_time_days, 0), s.lead_time_days, 0)
    )
  from public.inventory_levels l
  join public.reorder_rules r
    on r.product_id = l.product_id
   and r.location_id = l.location_id
   and r.is_active
  left join public.suppliers s
    on s.id = r.supplier_id
  where (l.on_hand - l.reserved) <= r.reorder_point
    and (p_location_id is null or l.location_id = p_location_id)
    and not exists (
      select 1
      from public.inventory_alerts a
      where a.product_id = l.product_id
        and a.location_id = l.location_id
        and a.alert_type = 'low_stock'
        and a.status in ('active', 'acknowledged')
    );

  get diagnostics v_inserted = row_count;
  return v_inserted;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(p."group") = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.reserve_inventory_for_order(p_order_id bigint, p_location_id bigint DEFAULT NULL::bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_location_id bigint;
  v_user_id uuid;
  v_item record;
  v_on_hand integer;
  v_reserved integer;
  v_new_on_hand integer;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to reserve inventory.';
  end if;

  if exists (
    select 1
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'sale'
  ) then
    return;
  end if;

  select user_id
    into v_user_id
  from public.orders
  where id = p_order_id;

  select coalesce(
    p_location_id,
    (
      select id
      from public.inventory_locations
      where is_active = true
      order by id
      limit 1
    )
  )
  into v_location_id;

  if v_location_id is null then
    raise exception 'No active inventory location available.';
  end if;

  for v_item in
    select product_id, quantity
    from public.order_items
    where order_id = p_order_id
  loop
    select on_hand, reserved
      into v_on_hand, v_reserved
    from public.inventory_levels
    where product_id = v_item.product_id
      and location_id = v_location_id
    for update;

    if v_on_hand is null then
      v_on_hand := 0;
    end if;
    if v_reserved is null then
      v_reserved := 0;
    end if;

    v_new_on_hand := v_on_hand - v_item.quantity;
    if v_new_on_hand < 0 then
      raise exception 'Insufficient stock for product %', v_item.product_id;
    end if;

    insert into public.inventory_levels (
      product_id,
      location_id,
      on_hand,
      reserved,
      status
    )
    values (
      v_item.product_id,
      v_location_id,
      v_new_on_hand,
      v_reserved,
      case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end
    )
    on conflict (product_id, location_id)
    do update set
      on_hand = excluded.on_hand,
      reserved = excluded.reserved,
      status = excluded.status;

    insert into public.inventory_transactions (
      product_id,
      location_id,
      movement_type,
      delta_on_hand,
      delta_reserved,
      on_hand_before,
      on_hand_after,
      reserved_before,
      reserved_after,
      reason,
      order_id,
      created_by,
      metadata
    )
    values (
      v_item.product_id,
      v_location_id,
      'sale',
      -v_item.quantity,
      0,
      v_on_hand,
      v_new_on_hand,
      v_reserved,
      v_reserved,
      'Order placed',
      p_order_id,
      v_user_id,
      jsonb_build_object('source', 'order')
    );
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.restock_inventory_for_order(p_order_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_item record;
  v_on_hand integer;
  v_reserved integer;
  v_new_on_hand integer;
  v_new_reserved integer;
  v_user_id uuid;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to restock inventory.';
  end if;

  if exists (
    select 1
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'return'
  ) then
    return;
  end if;

  select user_id
    into v_user_id
  from public.orders
  where id = p_order_id;

  for v_item in
    select product_id,
           location_id,
           sum(delta_on_hand) as delta_on_hand,
           sum(delta_reserved) as delta_reserved
    from public.inventory_transactions
    where order_id = p_order_id
      and movement_type = 'sale'
    group by product_id, location_id
  loop
    select on_hand, reserved
      into v_on_hand, v_reserved
    from public.inventory_levels
    where product_id = v_item.product_id
      and location_id = v_item.location_id
    for update;

    if v_on_hand is null then
      v_on_hand := 0;
    end if;
    if v_reserved is null then
      v_reserved := 0;
    end if;

    v_new_on_hand := v_on_hand - v_item.delta_on_hand;
    v_new_reserved := v_reserved - v_item.delta_reserved;

    if v_new_on_hand < 0 or v_new_reserved < 0 or v_new_reserved > v_new_on_hand then
      raise exception 'Invalid restock adjustment for product %', v_item.product_id;
    end if;

    update public.inventory_levels
      set on_hand = v_new_on_hand,
          reserved = v_new_reserved,
          status = case when v_new_on_hand > 0 then 'available' else 'out_of_stock' end
    where product_id = v_item.product_id
      and location_id = v_item.location_id;

    insert into public.inventory_transactions (
      product_id,
      location_id,
      movement_type,
      delta_on_hand,
      delta_reserved,
      on_hand_before,
      on_hand_after,
      reserved_before,
      reserved_after,
      reason,
      order_id,
      created_by,
      metadata
    )
    values (
      v_item.product_id,
      v_item.location_id,
      'return',
      -v_item.delta_on_hand,
      -v_item.delta_reserved,
      v_on_hand,
      v_new_on_hand,
      v_reserved,
      v_new_reserved,
      'Order cancelled',
      p_order_id,
      v_user_id,
      jsonb_build_object('source', 'order')
    );
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_inventory_levels_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_inventory_locations_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_reorder_rules_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."inventory_alerts" to "anon";

grant insert on table "public"."inventory_alerts" to "anon";

grant references on table "public"."inventory_alerts" to "anon";

grant select on table "public"."inventory_alerts" to "anon";

grant trigger on table "public"."inventory_alerts" to "anon";

grant truncate on table "public"."inventory_alerts" to "anon";

grant update on table "public"."inventory_alerts" to "anon";

grant delete on table "public"."inventory_alerts" to "authenticated";

grant insert on table "public"."inventory_alerts" to "authenticated";

grant references on table "public"."inventory_alerts" to "authenticated";

grant select on table "public"."inventory_alerts" to "authenticated";

grant trigger on table "public"."inventory_alerts" to "authenticated";

grant truncate on table "public"."inventory_alerts" to "authenticated";

grant update on table "public"."inventory_alerts" to "authenticated";

grant delete on table "public"."inventory_alerts" to "service_role";

grant insert on table "public"."inventory_alerts" to "service_role";

grant references on table "public"."inventory_alerts" to "service_role";

grant select on table "public"."inventory_alerts" to "service_role";

grant trigger on table "public"."inventory_alerts" to "service_role";

grant truncate on table "public"."inventory_alerts" to "service_role";

grant update on table "public"."inventory_alerts" to "service_role";

grant delete on table "public"."inventory_levels" to "anon";

grant insert on table "public"."inventory_levels" to "anon";

grant references on table "public"."inventory_levels" to "anon";

grant select on table "public"."inventory_levels" to "anon";

grant trigger on table "public"."inventory_levels" to "anon";

grant truncate on table "public"."inventory_levels" to "anon";

grant update on table "public"."inventory_levels" to "anon";

grant delete on table "public"."inventory_levels" to "authenticated";

grant insert on table "public"."inventory_levels" to "authenticated";

grant references on table "public"."inventory_levels" to "authenticated";

grant select on table "public"."inventory_levels" to "authenticated";

grant trigger on table "public"."inventory_levels" to "authenticated";

grant truncate on table "public"."inventory_levels" to "authenticated";

grant update on table "public"."inventory_levels" to "authenticated";

grant delete on table "public"."inventory_levels" to "service_role";

grant insert on table "public"."inventory_levels" to "service_role";

grant references on table "public"."inventory_levels" to "service_role";

grant select on table "public"."inventory_levels" to "service_role";

grant trigger on table "public"."inventory_levels" to "service_role";

grant truncate on table "public"."inventory_levels" to "service_role";

grant update on table "public"."inventory_levels" to "service_role";

grant delete on table "public"."inventory_locations" to "anon";

grant insert on table "public"."inventory_locations" to "anon";

grant references on table "public"."inventory_locations" to "anon";

grant select on table "public"."inventory_locations" to "anon";

grant trigger on table "public"."inventory_locations" to "anon";

grant truncate on table "public"."inventory_locations" to "anon";

grant update on table "public"."inventory_locations" to "anon";

grant delete on table "public"."inventory_locations" to "authenticated";

grant insert on table "public"."inventory_locations" to "authenticated";

grant references on table "public"."inventory_locations" to "authenticated";

grant select on table "public"."inventory_locations" to "authenticated";

grant trigger on table "public"."inventory_locations" to "authenticated";

grant truncate on table "public"."inventory_locations" to "authenticated";

grant update on table "public"."inventory_locations" to "authenticated";

grant delete on table "public"."inventory_locations" to "service_role";

grant insert on table "public"."inventory_locations" to "service_role";

grant references on table "public"."inventory_locations" to "service_role";

grant select on table "public"."inventory_locations" to "service_role";

grant trigger on table "public"."inventory_locations" to "service_role";

grant truncate on table "public"."inventory_locations" to "service_role";

grant update on table "public"."inventory_locations" to "service_role";

grant delete on table "public"."inventory_transactions" to "anon";

grant insert on table "public"."inventory_transactions" to "anon";

grant references on table "public"."inventory_transactions" to "anon";

grant select on table "public"."inventory_transactions" to "anon";

grant trigger on table "public"."inventory_transactions" to "anon";

grant truncate on table "public"."inventory_transactions" to "anon";

grant update on table "public"."inventory_transactions" to "anon";

grant delete on table "public"."inventory_transactions" to "authenticated";

grant insert on table "public"."inventory_transactions" to "authenticated";

grant references on table "public"."inventory_transactions" to "authenticated";

grant select on table "public"."inventory_transactions" to "authenticated";

grant trigger on table "public"."inventory_transactions" to "authenticated";

grant truncate on table "public"."inventory_transactions" to "authenticated";

grant update on table "public"."inventory_transactions" to "authenticated";

grant delete on table "public"."inventory_transactions" to "service_role";

grant insert on table "public"."inventory_transactions" to "service_role";

grant references on table "public"."inventory_transactions" to "service_role";

grant select on table "public"."inventory_transactions" to "service_role";

grant trigger on table "public"."inventory_transactions" to "service_role";

grant truncate on table "public"."inventory_transactions" to "service_role";

grant update on table "public"."inventory_transactions" to "service_role";

grant delete on table "public"."reorder_rules" to "anon";

grant insert on table "public"."reorder_rules" to "anon";

grant references on table "public"."reorder_rules" to "anon";

grant select on table "public"."reorder_rules" to "anon";

grant trigger on table "public"."reorder_rules" to "anon";

grant truncate on table "public"."reorder_rules" to "anon";

grant update on table "public"."reorder_rules" to "anon";

grant delete on table "public"."reorder_rules" to "authenticated";

grant insert on table "public"."reorder_rules" to "authenticated";

grant references on table "public"."reorder_rules" to "authenticated";

grant select on table "public"."reorder_rules" to "authenticated";

grant trigger on table "public"."reorder_rules" to "authenticated";

grant truncate on table "public"."reorder_rules" to "authenticated";

grant update on table "public"."reorder_rules" to "authenticated";

grant delete on table "public"."reorder_rules" to "service_role";

grant insert on table "public"."reorder_rules" to "service_role";

grant references on table "public"."reorder_rules" to "service_role";

grant select on table "public"."reorder_rules" to "service_role";

grant trigger on table "public"."reorder_rules" to "service_role";

grant truncate on table "public"."reorder_rules" to "service_role";

grant update on table "public"."reorder_rules" to "service_role";

grant delete on table "public"."suppliers" to "anon";

grant insert on table "public"."suppliers" to "anon";

grant references on table "public"."suppliers" to "anon";

grant select on table "public"."suppliers" to "anon";

grant trigger on table "public"."suppliers" to "anon";

grant truncate on table "public"."suppliers" to "anon";

grant update on table "public"."suppliers" to "anon";

grant delete on table "public"."suppliers" to "authenticated";

grant insert on table "public"."suppliers" to "authenticated";

grant references on table "public"."suppliers" to "authenticated";

grant select on table "public"."suppliers" to "authenticated";

grant trigger on table "public"."suppliers" to "authenticated";

grant truncate on table "public"."suppliers" to "authenticated";

grant update on table "public"."suppliers" to "authenticated";

grant delete on table "public"."suppliers" to "service_role";

grant insert on table "public"."suppliers" to "service_role";

grant references on table "public"."suppliers" to "service_role";

grant select on table "public"."suppliers" to "service_role";

grant trigger on table "public"."suppliers" to "service_role";

grant truncate on table "public"."suppliers" to "service_role";

grant update on table "public"."suppliers" to "service_role";


  create policy "inventory_alerts read admin"
  on "public"."inventory_alerts"
  as permissive
  for select
  to authenticated
using (public.is_admin());



  create policy "inventory_alerts update admin"
  on "public"."inventory_alerts"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "inventory_levels delete admin"
  on "public"."inventory_levels"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "inventory_levels insert admin"
  on "public"."inventory_levels"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "inventory_levels read"
  on "public"."inventory_levels"
  as permissive
  for select
  to authenticated
using (true);



  create policy "inventory_levels update admin"
  on "public"."inventory_levels"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "inventory_locations delete admin"
  on "public"."inventory_locations"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "inventory_locations insert admin"
  on "public"."inventory_locations"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "inventory_locations read"
  on "public"."inventory_locations"
  as permissive
  for select
  to authenticated
using (true);



  create policy "inventory_locations update admin"
  on "public"."inventory_locations"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "inventory_transactions insert admin"
  on "public"."inventory_transactions"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "inventory_transactions read admin"
  on "public"."inventory_transactions"
  as permissive
  for select
  to authenticated
using (public.is_admin());



  create policy "reorder_rules read admin"
  on "public"."reorder_rules"
  as permissive
  for select
  to authenticated
using (public.is_admin());



  create policy "reorder_rules update admin"
  on "public"."reorder_rules"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "reorder_rules write admin"
  on "public"."reorder_rules"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "suppliers read admin"
  on "public"."suppliers"
  as permissive
  for select
  to authenticated
using (public.is_admin());



  create policy "suppliers update admin"
  on "public"."suppliers"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "suppliers write admin"
  on "public"."suppliers"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());


CREATE TRIGGER trg_touch_inventory_levels_updated_at BEFORE UPDATE ON public.inventory_levels FOR EACH ROW EXECUTE FUNCTION public.touch_inventory_levels_updated_at();

CREATE TRIGGER trg_touch_inventory_locations_updated_at BEFORE UPDATE ON public.inventory_locations FOR EACH ROW EXECUTE FUNCTION public.touch_inventory_locations_updated_at();

CREATE TRIGGER trg_touch_reorder_rules_updated_at BEFORE UPDATE ON public.reorder_rules FOR EACH ROW EXECUTE FUNCTION public.touch_reorder_rules_updated_at();

