-- Sprint 3: Reorder rules, suppliers, and inventory alerts.

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  contact_email text,
  contact_phone text,
  lead_time_days integer not null default 0,
  is_active boolean not null default true,
  constraint suppliers_unique_name unique (name),
  constraint suppliers_lead_time_check check (lead_time_days >= 0)
);

create table if not exists public.reorder_rules (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  product_id bigint not null references public.products(id) on delete cascade,
  location_id bigint not null references public.inventory_locations(id) on delete cascade,
  supplier_id bigint references public.suppliers(id) on delete set null,
  reorder_point integer not null default 0,
  safety_stock integer not null default 0,
  lead_time_days integer not null default 0,
  is_active boolean not null default true,
  constraint reorder_rules_unique_product_location unique (product_id, location_id),
  constraint reorder_rules_non_negative check (
    reorder_point >= 0 and safety_stock >= 0 and lead_time_days >= 0
  )
);

create table if not exists public.inventory_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id) on delete set null,
  product_id bigint not null references public.products(id) on delete cascade,
  location_id bigint not null references public.inventory_locations(id) on delete cascade,
  alert_type text not null default 'low_stock',
  severity text not null default 'warning',
  status text not null default 'active',
  on_hand integer not null default 0,
  reserved integer not null default 0,
  available integer not null default 0,
  reorder_point integer not null default 0,
  safety_stock integer not null default 0,
  note text,
  metadata jsonb,
  constraint inventory_alerts_status_check check (
    status in ('active', 'acknowledged', 'resolved')
  )
);

create index if not exists idx_reorder_rules_location
  on public.reorder_rules (location_id);
create index if not exists idx_reorder_rules_product
  on public.reorder_rules (product_id);
create index if not exists idx_inventory_alerts_location
  on public.inventory_alerts (location_id);
create index if not exists idx_inventory_alerts_created_at
  on public.inventory_alerts (created_at desc);

create unique index if not exists idx_inventory_alerts_active_unique
  on public.inventory_alerts (product_id, location_id, alert_type)
  where status in ('active', 'acknowledged');

create or replace function public.touch_reorder_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_reorder_rules_updated_at on public.reorder_rules;
create trigger trg_touch_reorder_rules_updated_at
before update on public.reorder_rules
for each row execute function public.touch_reorder_rules_updated_at();

create or replace function public.generate_inventory_alerts(
  p_location_id bigint default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer := 0;
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to generate alerts.';
  end if;

  -- Resolve alerts where stock is back above reorder point.
  update public.inventory_alerts a
  set status = 'resolved',
      resolved_at = now()
  from public.inventory_levels l
  join public.reorder_rules r
    on r.product_id = l.product_id
   and r.location_id = l.location_id
   and r.is_active
  where a.product_id = l.product_id
    and a.location_id = l.location_id
    and a.alert_type = 'low_stock'
    and a.status in ('active', 'acknowledged')
    and (l.on_hand - l.reserved) > r.reorder_point
    and (p_location_id is null or l.location_id = p_location_id);

  insert into public.inventory_alerts (
    product_id,
    location_id,
    alert_type,
    severity,
    status,
    on_hand,
    reserved,
    available,
    reorder_point,
    safety_stock,
    note,
    metadata
  )
  select
    l.product_id,
    l.location_id,
    'low_stock',
    case
      when (l.on_hand - l.reserved) <= r.safety_stock then 'critical'
      else 'warning'
    end,
    'active',
    l.on_hand,
    l.reserved,
    (l.on_hand - l.reserved) as available,
    r.reorder_point,
    r.safety_stock,
    'Reorder point reached',
    jsonb_build_object(
      'lead_time_days',
      coalesce(nullif(r.lead_time_days, 0), s.lead_time_days, 0)
    )
  from public.inventory_levels l
  join public.reorder_rules r
    on r.product_id = l.product_id
   and r.location_id = l.location_id
   and r.is_active
  left join public.suppliers s
    on s.id = r.supplier_id
  where (l.on_hand - l.reserved) <= r.reorder_point
    and (p_location_id is null or l.location_id = p_location_id)
    and not exists (
      select 1
      from public.inventory_alerts a
      where a.product_id = l.product_id
        and a.location_id = l.location_id
        and a.alert_type = 'low_stock'
        and a.status in ('active', 'acknowledged')
    );

  get diagnostics v_inserted = row_count;
  return v_inserted;
end;
$$;

create or replace function public.acknowledge_inventory_alert(
  p_alert_id bigint,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (public.is_admin() or auth.role() = 'service_role') then
    raise exception 'Not authorized to acknowledge alerts.';
  end if;

  update public.inventory_alerts
  set status = 'acknowledged',
      acknowledged_at = now(),
      acknowledged_by = auth.uid(),
      note = coalesce(p_note, note)
  where id = p_alert_id
    and status in ('active', 'acknowledged');
end;
$$;

alter table public.suppliers enable row level security;
alter table public.reorder_rules enable row level security;
alter table public.inventory_alerts enable row level security;

drop policy if exists "suppliers read admin" on public.suppliers;
create policy "suppliers read admin"
on public.suppliers
for select
to authenticated
using (public.is_admin());

drop policy if exists "suppliers write admin" on public.suppliers;
create policy "suppliers write admin"
on public.suppliers
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "suppliers update admin" on public.suppliers;
create policy "suppliers update admin"
on public.suppliers
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "reorder_rules read admin" on public.reorder_rules;
create policy "reorder_rules read admin"
on public.reorder_rules
for select
to authenticated
using (public.is_admin());

drop policy if exists "reorder_rules write admin" on public.reorder_rules;
create policy "reorder_rules write admin"
on public.reorder_rules
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "reorder_rules update admin" on public.reorder_rules;
create policy "reorder_rules update admin"
on public.reorder_rules
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "inventory_alerts read admin" on public.inventory_alerts;
create policy "inventory_alerts read admin"
on public.inventory_alerts
for select
to authenticated
using (public.is_admin());

drop policy if exists "inventory_alerts update admin" on public.inventory_alerts;
create policy "inventory_alerts update admin"
on public.inventory_alerts
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select, insert, update on table
  public.suppliers,
  public.reorder_rules,
  public.inventory_alerts
to authenticated, service_role;

grant execute on function public.generate_inventory_alerts(bigint) to authenticated, service_role;
grant execute on function public.acknowledge_inventory_alert(bigint, text) to authenticated, service_role;
