-- Store verified payment webhook deliveries for auditability and idempotency.

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  gateway text not null,
  gateway_event_id text not null,
  event_type text,
  payment_transaction_id uuid references public.payment_transactions(id) on delete set null,
  payload jsonb not null,
  processed_at timestamptz,
  processing_error text
);

alter table public.payment_webhook_events
  drop constraint if exists payment_webhook_events_gateway_check;
alter table public.payment_webhook_events
  add constraint payment_webhook_events_gateway_check
  check (gateway in ('yoco', 'payfast', 'ozow'));

create unique index if not exists idx_payment_webhook_events_gateway_event
  on public.payment_webhook_events (gateway, gateway_event_id);

create index if not exists idx_payment_webhook_events_transaction
  on public.payment_webhook_events (payment_transaction_id);

alter table public.payment_webhook_events enable row level security;

drop policy if exists "payment_webhook_events service role read" on public.payment_webhook_events;
create policy "payment_webhook_events service role read"
on public.payment_webhook_events
for select
to service_role
using (true);

drop policy if exists "payment_webhook_events service role insert" on public.payment_webhook_events;
create policy "payment_webhook_events service role insert"
on public.payment_webhook_events
for insert
to service_role
with check (true);

drop policy if exists "payment_webhook_events service role update" on public.payment_webhook_events;
create policy "payment_webhook_events service role update"
on public.payment_webhook_events
for update
to service_role
using (true)
with check (true);

grant select, insert, update on table public.payment_webhook_events
to service_role;
