-- Inventory foundation tables (locations + stock levels) and product identifiers.

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(p."group") = 'admin'
  );
$$;

create table if not exists public.inventory_locations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  code text unique,
  address text,
  is_active boolean not null default true
);

create table if not exists public.inventory_levels (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  product_id bigint not null references public.products(id) on delete cascade,
  location_id bigint not null references public.inventory_locations(id) on delete cascade,
  on_hand integer not null default 0,
  reserved integer not null default 0,
  status text not null default 'available',
  constraint inventory_levels_on_hand_check check (on_hand >= 0),
  constraint inventory_levels_reserved_check check (reserved >= 0),
  constraint inventory_levels_unique_product_location unique (product_id, location_id)
);

create index if not exists idx_inventory_levels_product
  on public.inventory_levels (product_id);
create index if not exists idx_inventory_levels_location
  on public.inventory_levels (location_id);

alter table public.products
  add column if not exists sku text,
  add column if not exists barcode text,
  add column if not exists track_inventory boolean not null default true,
  add column if not exists unit_cost numeric not null default 0;

create or replace function public.touch_inventory_locations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.touch_inventory_levels_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_inventory_locations_updated_at on public.inventory_locations;
create trigger trg_touch_inventory_locations_updated_at
before update on public.inventory_locations
for each row execute function public.touch_inventory_locations_updated_at();

drop trigger if exists trg_touch_inventory_levels_updated_at on public.inventory_levels;
create trigger trg_touch_inventory_levels_updated_at
before update on public.inventory_levels
for each row execute function public.touch_inventory_levels_updated_at();

alter table public.inventory_locations enable row level security;
alter table public.inventory_levels enable row level security;

drop policy if exists "inventory_locations read" on public.inventory_locations;
create policy "inventory_locations read"
on public.inventory_locations
for select
to authenticated
using (true);

drop policy if exists "inventory_locations write admin" on public.inventory_locations;
drop policy if exists "inventory_locations insert admin" on public.inventory_locations;
drop policy if exists "inventory_locations update admin" on public.inventory_locations;
drop policy if exists "inventory_locations delete admin" on public.inventory_locations;
create policy "inventory_locations insert admin"
on public.inventory_locations
for insert
to authenticated
with check (public.is_admin());
create policy "inventory_locations update admin"
on public.inventory_locations
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
create policy "inventory_locations delete admin"
on public.inventory_locations
for delete
to authenticated
using (public.is_admin());

drop policy if exists "inventory_levels read" on public.inventory_levels;
create policy "inventory_levels read"
on public.inventory_levels
for select
to authenticated
using (true);

drop policy if exists "inventory_levels write admin" on public.inventory_levels;
drop policy if exists "inventory_levels insert admin" on public.inventory_levels;
drop policy if exists "inventory_levels update admin" on public.inventory_levels;
drop policy if exists "inventory_levels delete admin" on public.inventory_levels;
create policy "inventory_levels insert admin"
on public.inventory_levels
for insert
to authenticated
with check (public.is_admin());
create policy "inventory_levels update admin"
on public.inventory_levels
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
create policy "inventory_levels delete admin"
on public.inventory_levels
for delete
to authenticated
using (public.is_admin());

grant select, insert, update, delete on table
  public.inventory_locations,
  public.inventory_levels
to authenticated, service_role;

grant usage, select on all sequences in schema public to authenticated, service_role;
