-- Bootstrap core schema for local environments.
-- This migration is intentionally idempotent so it can run safely on existing DBs.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  mobile_number text,
  "group" text not null default 'user',
  full_name text,
  username text,
  avatar_url text,
  website text,
  updated_at timestamptz default now(),
  first_name text,
  surname text,
  delivery_address text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  description text,
  image text,
  in_stock boolean not null default true,
  is_active boolean not null default true,
  price numeric not null default 0
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'New',
  total numeric not null default 0,
  user_id uuid references public.profiles(id) on delete set null,
  delivery_option text not null default 'Delivery'
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer default 1,
  size text not null default 'M'
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Local-friendly baseline policies.
drop policy if exists "profiles open access" on public.profiles;
create policy "profiles open access"
on public.profiles
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "products open access" on public.products;
create policy "products open access"
on public.products
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "orders open access" on public.orders;
create policy "orders open access"
on public.orders
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "order_items open access" on public.order_items;
create policy "order_items open access"
on public.order_items
for all
to anon, authenticated
using (true)
with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table
  public.profiles,
  public.products,
  public.orders,
  public.order_items
to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;
